### PR TITLE
feat: fetch data from specified device

### PR DESCRIPTION
**Pull request by benneb2**

### CODE REVIEW

**Comment by haemishkyd** [comment]
Have you tested this change with multiple poolsense devices? I only have one so I can't. Thanks for doing this by the way.

**Comment by benneb2** [comment]
Yes ive tested it locally 
When you add the device, you can specify the deviceID, or it will default to the registration

Screenshot 2021-09-10 at 13 45 06

**Comment by benneb2** [comment]
@haemishkyd I pushed some updates to fetch the 1st device if its not passed with the form

**Comment by benneb2** [comment]
Also bumped the version to 0.1.0

**Comment by haemishkyd** [comment]
The new version of the pypi package has been uploaded. Let me know if there is anything else I can do.

**Pull request merged**
